export const reducerCases={
    SET_USER_INFO: "SET_USER_INFO",
    SET_NEW_USER: "SET_NEW_USER",
    SET_ALL_CONTACTS_PAGE:"SET_ALL_CONTACTS_PAGE",
    SET_MESSAGES:"SET_MESSAGES",
    SET_SOCKET:"SET_SOCKET",
    ADD_MESSAGE:"ADD_MESSAGE"
}; 